<?php
declare (strict_types = 1);

namespace app\controller;


use app\BaseController;
use app\service\AdminService;

class Login extends BaseController
{
    protected $service;

    // 初始化
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->service = new AdminService();  // 管理员登录基于管理员信息表，实例化管理员服务
    }

    /**
     * 管理员登录
     */
    public function login()
    {
        $username = input('username'); // 接收username字段
        $password = input('password'); // 接收password字段
        // 验证是否输入用户名和密码
        if (!$username) {
            return error('请输入用户名');
        }
        if (!$password) {
            return error('请输入密码');
        }
        // 验证通过后调用当前服务中登录方法，对输入的用户名和密码进行验证
        $result = $this->service->login($username, $password);
        if ($result) {
            return success($result, '登录成功'); // 返回token
        } else {
            return error('用户名或密码错误');
        }
    }

    /**
     * 退出登录
     */
    public function logout() {
        return success('退出登录');
    }
}
